# Generated by Django 4.2.6 on 2023-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/hotel.jpg')),
                ('price', models.IntegerField()),
                ('details', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(upload_to='image/hotel.jpg'),
        ),
    ]
