# Generated by Django 4.2.6 on 2023-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0002_user_alter_addproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ureview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
    ]
